### PR TITLE
implementing new plotting formats, including standard deviation

### PR DESCRIPTION
**Pull request by gast-ben**
Will be followed by a notebook for analysis of one station each. Automation should ensure that this works for each of the regarded stations. Closing #2 and #12.

### CODE REVIEW

**Comment by kuchaale** [comment]
Can you try logarithmic color scale for GW and PW activity?
```python
from matplotlib import colors

levs = np.logspace(0, 3.0, num=21)
da.plot.contourf(x = 'lag', levels = levs, norm=colors.LogNorm(), extend = 'both')
```

**Comment by gast-ben** [comment]
Logarithmic color scale was applied for GW and PW activity climatologies. (see [last commit](https://github.com/VACILT/SSW_project/pull/13/commits/480c21b2e346db07a3ab2258f91fa707a518340c))
For anomalies it was not possible because of negative values.

**Comment by kuchaale** [comment]
Can you set the same lag extent for all variables? I think [-40,40] may be sufficient.

**Comment by gast-ben** [comment]
Syntax for running papermill:
 **papermill input_notebook.ipynb output_notebook.ipynb -p parameter_name parameter_value**

Example code:
 **papermill analysis_per_station.ipynb analysis_Esrange.ipynb -p station 'Esrange'**

**Pull request closed without merging**
